import localFont from 'next/font/local';
import './globals.css';
import Navbar from './components/layout/Navbar';
import Footer from './components/layout/Footer';

const gallient = localFont({
  src: '../public/font/Gallient.ttf',
  variable: '--font-gallient',
  // weight: '100 900',
});

const inter = localFont({
  src: '../public/font/Inter_Regular.ttf',
  variable: '--font-inter',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={` ${gallient.variable} ${inter.variable} antialiased `}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
